import { Stack, useRouter } from "expo-router";
import * as Notifications from "expo-notifications";
import * as SplashScreen from "expo-splash-screen";
import React, { useCallback, useEffect } from "react";
import {
  LogBox,
  Platform,
  StatusBar,
} from "react-native";
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { doc, getDoc } from "firebase/firestore";

import { auth, db } from "@/src/config/firebase";

import { ToastProvider } from "@/src/components/Toast";
import { COLORS } from "@/src/config/theme";
import { AppProvider } from "@/src/context/AppContext";
import { NotificationProvider } from "@/src/context/NotificationContext";
import { ProductProvider } from "@/src/context/ProductContext";
import { useIconFonts } from "@/src/hooks/use-icon-fonts";
import {
  setupNotificationHandler,
  startPushTokenRegistrationLifecycle,
} from "@/src/services/pushNotifications";

LogBox.ignoreAllLogs(true);

void SplashScreen.preventAutoHideAsync();

setupNotificationHandler();

function getSafeNotificationRoute(
  data: Record<string, any> | undefined,
): string | null {
  const orderId =
    typeof data?.orderId === "string"
      ? data.orderId.trim()
      : "";

  // Admin new-order notifications must stay inside the protected
  // admin flow instead of opening the customer order route.
  if (
    data?.type === "admin_new_order" &&
    orderId
  ) {
    return (
      `/admin/orders?orderId=${encodeURIComponent(orderId)}`
    );
  }

  // Customer order notifications open the customer order-detail route.
  if (orderId) {
    return `/order/${encodeURIComponent(orderId)}`;
  }

  let route =
    typeof data?.route === "string"
      ? data.route.trim()
      : "";

  if (!route) {
    return null;
  }

  // Never try to navigate to a bare custom scheme.
  if (
    route === "rahasupermarket://" ||
    route === "rahasupermarket:///" ||
    route === "/"
  ) {
    return null;
  }

  // Convert full app deep-links into Expo Router paths.
  if (route.startsWith("rahasupermarket://")) {
    route = route.replace(
      /^rahasupermarket:\/\/\/?/,
      "/",
    );
  }

  // Expo Router route groups such as (tabs) are not part of the URL.
  route = route.replace(
    /^\/\(tabs\)(?=\/|$)/,
    "",
  );

  // Support notifications generated by older app code.
  if (route.startsWith("/orders/")) {
    route = route.replace(
      /^\/orders\//,
      "/order/",
    );
  }

  if (!route || route === "/") {
    return null;
  }

  if (!route.startsWith("/")) {
    route = `/${route}`;
  }

  return route;
}

export default function RootLayout() {
  const [loaded, error] = useIconFonts();
  const router = useRouter();

  const handleNotificationResponse = useCallback(
    async (
      response: Notifications.NotificationResponse,
    ) => {
      const data =
        response.notification.request.content.data as
          | Record<string, any>
          | undefined;

      const orderId =
        typeof data?.orderId === "string"
          ? data.orderId.trim()
          : "";

      // Admin order alerts require a currently authenticated,
      // active administrator before the order screen can open.
      if (
        data?.type === "admin_new_order" &&
        orderId
      ) {
        const user = auth.currentUser;

        if (!user) {
          router.push({
            pathname: "/admin/login",
            params: { orderId },
          } as never);
          return;
        }

        try {
          const adminSnapshot = await getDoc(
            doc(db, "admins", user.uid),
          );

          const adminData = adminSnapshot.exists()
            ? adminSnapshot.data()
            : null;

          const isAuthorizedAdmin =
            adminData?.role === "admin" &&
            adminData?.active === true;

          if (!isAuthorizedAdmin) {
            router.push({
              pathname: "/admin/login",
              params: { orderId },
            } as never);
            return;
          }

          router.push({
            pathname: "/admin/orders",
            params: { orderId },
          } as never);
          return;
        } catch (adminCheckError) {
          console.error(
            "[Push] Admin authorization check failed:",
            adminCheckError,
          );

          router.push({
            pathname: "/admin/login",
            params: { orderId },
          } as never);
          return;
        }
      }

      const destination =
        getSafeNotificationRoute(data);

      if (destination) {
        router.push(destination as never);
        return;
      }

      // Safe fallback instead of opening an unmatched root deep-link.
      router.push("/notifications" as never);
    },
    [router],
  );

  useEffect(() => {
    if (loaded || error) {
      void SplashScreen.hideAsync();
    }
  }, [loaded, error]);

  useEffect(() => {
    const stopPushRegistration =
      startPushTokenRegistrationLifecycle();

    return stopPushRegistration;
  }, []);

  useEffect(() => {
    if (Platform.OS === "web") {
      return;
    }

    const subscription =
      Notifications.addNotificationResponseReceivedListener(
        handleNotificationResponse,
      );

    return () => {
      subscription.remove();
    };
  }, [handleNotificationResponse]);

  useEffect(() => {
    if (
      Platform.OS === "web" ||
      (!loaded && !error)
    ) {
      return;
    }

    const timer = setTimeout(() => {
      void Notifications.getLastNotificationResponseAsync()
        .then((response) => {
          if (!response) {
            return;
          }

          handleNotificationResponse(response);
        })
        .catch((notificationError) => {
          console.error(
            "[Push] Initial notification response failed:",
            notificationError,
          );
        });
    }, 300);

    return () => {
      clearTimeout(timer);
    };
  }, [
    loaded,
    error,
    handleNotificationResponse,
  ]);

  if (!loaded && !error) {
    return null;
  }

  return (
    <GestureHandlerRootView
      style={{ flex: 1 }}
    >
      <SafeAreaProvider>
        <ProductProvider>
          <AppProvider>
            <NotificationProvider>
              <ToastProvider>
                <StatusBar
                  barStyle="dark-content"
                  backgroundColor={
                    COLORS.background
                  }
                />

                <Stack
                  screenOptions={{
                    headerShown: false,
                    contentStyle: {
                      backgroundColor:
                        COLORS.background,
                    },
                  }}
                />
              </ToastProvider>
            </NotificationProvider>
          </AppProvider>
        </ProductProvider>
      </SafeAreaProvider>
    </GestureHandlerRootView>
  );
}

